# Fix Neovim colors while inside tmux
set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Enable mouse support
set -g mouse on

# Start counting windows/panes from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Override escape-time (set to 0 by tmux-sensible)
set -sg escape-time 1

# Restore clear-screen functionality (by setting it to <prefix> C-l)
bind C-l send-keys 'C-l'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
